name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    name: Build, Test
    strategy:
      matrix:
        version: [16, 17, 18]
        os: [ubuntu-latest, windows-latest]
    timeout-minutes: 15
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          ref: ${{github.event.pull_request.head.sha}}
          fetch-depth: 0

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}
          cache: "yarn"

      - name: Install dependencies
        run: yarn install

      - name: Test
        run: yarn run test

      - name: Changeset
        if: ${{ !contains(github.head_ref, 'changeset-release/main') }}
        run: |
          echo ${{github.head_ref}}
          echo ${{ !contains(github.head_ref, 'changeset-release/main') }}
          yarn changeset status --since origin/main
